//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2022.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Input {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2022.Test.Input", typeof(Input).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2991
        ///13880
        ///13279
        ///1514
        ///9507
        ///
        ///6544
        ///9672
        ///13044
        ///4794
        ///6648
        ///8669
        ///
        ///2790
        ///1196
        ///3619
        ///1692
        ///8727
        ///2342
        ///1099
        ///6083
        ///3834
        ///2008
        ///
        ///2974
        ///4393
        ///1146
        ///4240
        ///1880
        ///3226
        ///2390
        ///5640
        ///2768
        ///1887
        ///4217
        ///3314
        ///5653
        ///2609
        ///
        ///4473
        ///7306
        ///7909
        ///6862
        ///7413
        ///3738
        ///2102
        ///4269
        ///5966
        ///7491
        ///4851
        ///
        ///10396
        ///24686
        ///9258
        ///
        ///1299
        ///8539
        ///7570
        ///4888
        ///2209
        ///2720
        ///9275
        ///4843
        ///1884
        ///
        ///2421
        ///1872
        ///4696
        ///14627
        ///7944
        ///
        ///28659
        ///27933
        ///
        ///3477
        ///3702
        ///9649
        ///3433
        ///3288
        ///5779
        ///3578
        ///5744
        ///
        ///14516
        ///18228
        ///6351
        ///
        ///23055
        ///35889
        ///
        ///1539
        ///88 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01_Actual {
            get {
                return ResourceManager.GetString("Day01-Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000
        ///2000
        ///3000
        ///
        ///4000
        ///
        ///5000
        ///6000
        ///
        ///7000
        ///8000
        ///9000
        ///
        ///10000.
        /// </summary>
        internal static string Day01_Test {
            get {
                return ResourceManager.GetString("Day01-Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C X
        ///C X
        ///C X
        ///A Z
        ///C X
        ///C X
        ///A Y
        ///B X
        ///B Y
        ///B Z
        ///C Y
        ///C X
        ///C X
        ///C Y
        ///B Y
        ///C X
        ///C Y
        ///B Z
        ///C Y
        ///B Z
        ///B Z
        ///A Z
        ///C X
        ///C X
        ///C X
        ///B Z
        ///C Y
        ///C X
        ///C X
        ///B Y
        ///C X
        ///B Z
        ///C X
        ///C X
        ///A Y
        ///C X
        ///A Z
        ///B Z
        ///B Z
        ///B Z
        ///B Y
        ///B Z
        ///C X
        ///B Y
        ///C Y
        ///C Y
        ///B Z
        ///C X
        ///C Y
        ///C X
        ///C X
        ///C X
        ///C Y
        ///A X
        ///A X
        ///C Z
        ///C X
        ///B Z
        ///A Z
        ///C X
        ///B Y
        ///C Y
        ///B X
        ///B Z
        ///C Z
        ///A X
        ///C X
        ///B X
        ///C Y
        ///C Y
        ///B Z
        ///B Z
        ///B Z
        ///C Z
        ///A Z
        ///A Z
        ///C X
        ///C X
        ///C Z
        ///B Z
        ///B Y
        ///C X
        ///A Z
        ///C X
        ///B Y
        ///C Y
        ///B Z
        ///C X
        ///A Y
        ///C Y
        ///A X
        ///B Z
        ///C Y
        ///C Y
        ///C X
        ///C Y
        ///C X
        ///B X
        ///C Y
        ///C X
        ///B Y
        ///A Z
        ///B  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02_Actual {
            get {
                return ResourceManager.GetString("Day02-Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Y
        ///B X
        ///C Z.
        /// </summary>
        internal static string Day02_Test {
            get {
                return ResourceManager.GetString("Day02-Test", resourceCulture);
            }
        }
    }
}
